apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard  # Reference to the storage class for k3d
  hostPath:
    path: /home/laptopdev/Kubernetes/PrivateDockerRegistry/registry/repos  # Path to where data will be stored in the container
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube  # Ensure the volume is attached to the minikube node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
